import type { SearchResponse } from '@/types/search-types';

export const mockSearchResponse: SearchResponse = {
  resolvedAddress: 'Tingvej 4A, 2300 København S, Danmark',
  search: {
    address: 'Tingvej 4A, 2300 København S',
    accessMode: 'walk',
    radiusKm: null,
    maxWalkKm: 1,
    maxTransitMin: null,
    queries: ['hakket oksekød', 'kyllingebrystfilet', 'skyr'],
  },
  chains: [
    { chainId: 'netto', name: 'Netto' },
    { chainId: 'lidl', name: 'Lidl' },
    { chainId: 'foetex', name: 'føtex' },
    { chainId: 'rema1000', name: 'REMA 1000' },
    { chainId: 'meny', name: 'Meny' },
  ],
  stores: [
    {
      storeId: 'netto-amagerbrogade-001',
      chainId: 'netto',
      name: 'Netto Amagerbrogade',
      distanceMeters: 650,
      accessQualified: true,
      relevantOfferCount: 3,
    },
    {
      storeId: 'lidl-amagerbrogade-002',
      chainId: 'lidl',
      name: 'Lidl Amagerbrogade',
      distanceMeters: 900,
      accessQualified: true,
      relevantOfferCount: 2,
    },
    {
      storeId: 'foetex-fields-003',
      chainId: 'foetex',
      name: 'føtex Fields',
      distanceMeters: 1200,
      accessQualified: false,
      relevantOfferCount: 2,
    },
    {
      storeId: 'rema1000-oresundsvej-004',
      chainId: 'rema1000',
      name: 'REMA 1000 Øresundsvej',
      distanceMeters: 700,
      accessQualified: true,
      relevantOfferCount: 2,
    },
    {
      storeId: 'meny-vermlandsgade-005',
      chainId: 'meny',
      name: 'Meny Vermlandsgade',
      distanceMeters: 1500,
      accessQualified: false,
      relevantOfferCount: 1,
    },
  ],
  bestNow: [
    {
      offerId: 'offer-netto-okse-001',
      query: 'hakket oksekød',
      chainId: 'netto',
      chainName: 'Netto',
      storeId: 'netto-amagerbrogade-001',
      storeName: 'Netto Amagerbrogade',
      productTitle: 'Hakket oksekød 8-12%',
      price: 35,
      currency: 'DKK',
      sizeText: '400 g',
      unitPriceText: '87,50 kr/kg',
      distanceMeters: 650,
      validFrom: '2026-04-05',
      validTo: '2026-04-09',
      sourceKind: 'direct',
      sourceLabel: 'Tjek',
      sourceUrl: 'https://example.com/netto-hakket-okse',
      flags: ['direct_source'],
      confidence: 'high',
    },
    {
      offerId: 'offer-lidl-kylling-002',
      query: 'kyllingebrystfilet',
      chainId: 'lidl',
      chainName: 'Lidl',
      storeId: 'lidl-amagerbrogade-002',
      storeName: 'Lidl Amagerbrogade',
      productTitle: 'Kyllingebrystfilet',
      price: 45,
      currency: 'DKK',
      sizeText: '600 g',
      unitPriceText: '75,00 kr/kg',
      distanceMeters: 900,
      validFrom: '2026-04-05',
      validTo: '2026-04-08',
      sourceKind: 'direct',
      sourceLabel: 'Lidl',
      sourceUrl: 'https://example.com/lidl-kylling',
      flags: ['direct_source', 'app_price'],
      confidence: 'high',
    },
    {
      offerId: 'offer-rema-skyr-003',
      query: 'skyr',
      chainId: 'rema1000',
      chainName: 'REMA 1000',
      storeId: 'rema1000-oresundsvej-004',
      storeName: 'REMA 1000 Øresundsvej',
      productTitle: 'Skyr naturel',
      price: 20,
      currency: 'DKK',
      sizeText: '1 kg',
      unitPriceText: '20,00 kr/kg',
      distanceMeters: 700,
      validFrom: '2026-04-04',
      validTo: '2026-04-10',
      sourceKind: 'direct',
      sourceLabel: 'Tjek',
      sourceUrl: 'https://example.com/rema-skyr',
      flags: ['direct_source'],
      confidence: 'high',
    },
  ],
  upcoming: [
    {
      offerId: 'offer-foetex-okse-004',
      query: 'hakket oksekød',
      chainId: 'foetex',
      chainName: 'føtex',
      storeId: 'foetex-fields-003',
      storeName: 'føtex Fields',
      productTitle: 'Hakket oksekød 8-12%',
      price: 30,
      currency: 'DKK',
      sizeText: '400 g',
      unitPriceText: '75,00 kr/kg',
      distanceMeters: 1200,
      validFrom: '2026-04-07',
      validTo: '2026-04-12',
      sourceKind: 'direct',
      sourceLabel: 'iPaper',
      sourceUrl: 'https://example.com/foetex-okse',
      flags: ['direct_source', 'starts_soon'],
      confidence: 'high',
    },
    {
      offerId: 'offer-meny-kylling-005',
      query: 'kyllingebrystfilet',
      chainId: 'meny',
      chainName: 'Meny',
      storeId: 'meny-vermlandsgade-005',
      storeName: 'Meny Vermlandsgade',
      productTitle: 'Kyllingebryst inderfilet',
      price: 49,
      currency: 'DKK',
      sizeText: '500 g',
      unitPriceText: '98,00 kr/kg',
      distanceMeters: 1500,
      validFrom: '2026-04-08',
      validTo: '2026-04-13',
      sourceKind: 'fallback',
      sourceLabel: 'eTilbudsavis',
      sourceUrl: 'https://example.com/meny-kylling',
      flags: ['fallback_source', 'starts_soon', 'ambiguous_match'],
      confidence: 'medium',
    },
  ],
  offerGroups: [
    {
      query: 'hakket oksekød',
      offers: [
        {
          offerId: 'offer-netto-okse-001',
          query: 'hakket oksekød',
          chainId: 'netto',
          chainName: 'Netto',
          storeId: 'netto-amagerbrogade-001',
          storeName: 'Netto Amagerbrogade',
          productTitle: 'Hakket oksekød 8-12%',
          price: 35,
          currency: 'DKK',
          sizeText: '400 g',
          unitPriceText: '87,50 kr/kg',
          distanceMeters: 650,
          validFrom: '2026-04-05',
          validTo: '2026-04-09',
          sourceKind: 'direct',
          sourceLabel: 'Tjek',
          sourceUrl: 'https://example.com/netto-hakket-okse',
          flags: ['direct_source'],
          confidence: 'high',
        },
        {
          offerId: 'offer-foetex-okse-004',
          query: 'hakket oksekød',
          chainId: 'foetex',
          chainName: 'føtex',
          storeId: 'foetex-fields-003',
          storeName: 'føtex Fields',
          productTitle: 'Hakket oksekød 8-12%',
          price: 30,
          currency: 'DKK',
          sizeText: '400 g',
          unitPriceText: '75,00 kr/kg',
          distanceMeters: 1200,
          validFrom: '2026-04-07',
          validTo: '2026-04-12',
          sourceKind: 'direct',
          sourceLabel: 'iPaper',
          sourceUrl: 'https://example.com/foetex-okse',
          flags: ['direct_source', 'starts_soon'],
          confidence: 'high',
        }
      ]
    },
    {
      query: 'kyllingebrystfilet',
      offers: [
        {
          offerId: 'offer-lidl-kylling-002',
          query: 'kyllingebrystfilet',
          chainId: 'lidl',
          chainName: 'Lidl',
          storeId: 'lidl-amagerbrogade-002',
          storeName: 'Lidl Amagerbrogade',
          productTitle: 'Kyllingebrystfilet',
          price: 45,
          currency: 'DKK',
          sizeText: '600 g',
          unitPriceText: '75,00 kr/kg',
          distanceMeters: 900,
          validFrom: '2026-04-05',
          validTo: '2026-04-08',
          sourceKind: 'direct',
          sourceLabel: 'Lidl',
          sourceUrl: 'https://example.com/lidl-kylling',
          flags: ['direct_source', 'app_price'],
          confidence: 'high',
        },
        {
          offerId: 'offer-meny-kylling-005',
          query: 'kyllingebrystfilet',
          chainId: 'meny',
          chainName: 'Meny',
          storeId: 'meny-vermlandsgade-005',
          storeName: 'Meny Vermlandsgade',
          productTitle: 'Kyllingebryst inderfilet',
          price: 49,
          currency: 'DKK',
          sizeText: '500 g',
          unitPriceText: '98,00 kr/kg',
          distanceMeters: 1500,
          validFrom: '2026-04-08',
          validTo: '2026-04-13',
          sourceKind: 'fallback',
          sourceLabel: 'eTilbudsavis',
          sourceUrl: 'https://example.com/meny-kylling',
          flags: ['fallback_source', 'starts_soon', 'ambiguous_match'],
          confidence: 'medium',
        }
      ]
    },
    {
      query: 'skyr',
      offers: [
        {
          offerId: 'offer-rema-skyr-003',
          query: 'skyr',
          chainId: 'rema1000',
          chainName: 'REMA 1000',
          storeId: 'rema1000-oresundsvej-004',
          storeName: 'REMA 1000 Øresundsvej',
          productTitle: 'Skyr naturel',
          price: 20,
          currency: 'DKK',
          sizeText: '1 kg',
          unitPriceText: '20,00 kr/kg',
          distanceMeters: 700,
          validFrom: '2026-04-04',
          validTo: '2026-04-10',
          sourceKind: 'direct',
          sourceLabel: 'Tjek',
          sourceUrl: 'https://example.com/rema-skyr',
          flags: ['direct_source'],
          confidence: 'high',
        }
      ]
    }
  ],
  summary: {
    totalStoresInScope: 3,
    totalOffersMatched: 5,
    generatedAt: '2026-04-05T10:49:00Z'
  }
};
